# Generated by Django 2.0.2 on 2018-06-05 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('name', models.CharField(default='', max_length=250)),
                ('max_pics', models.PositiveSmallIntegerField(default=0)),
                ('max_gb', models.PositiveSmallIntegerField(default=1)),
                ('max_days', models.PositiveSmallIntegerField(default=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
